image: gcc

stages:
  - build

build:
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get install --yes git cmake build-essential libeigen3-dev libboost-all-dev
    - git clone https://github.com/lava/matplotlib-cpp.git /tmp/matplotlibcpp
    - cd /tmp/matplotlibcpp/ && make build && cd build
    - cmake .. && sudo make install

  script:
    - cd ~/ https://gitlab.com/cursoseaulas/robotics-codes.git
    - cd robotics-codes && make build
  only:
    - master

